dataClass/01.pt/pt0204/sPjt/home/urls.py
from . import views
from django.urls import include, path

app_name=""  #app별칭등록
urlpatterns = [
    path('', views.index,name='index'),
]

dataClass/01.pt/pt0204/sPjt/sPjt/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('', include('home.urls')),
]

dataClass/01.pt/pt0204/sPjt/students/urls.py
from . import views
from django.urls import include, path

app_name="students"  #app별칭등록
urlpatterns = [
    path('reg/', views.regStudent,name='reg'),
    path('regCon/', views.regStuCon,name='regCon'),
]

dataClass/01.pt/pt0204/sPjt/students/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    s_name = models.CharField(max_length=100)
    s_major = models.CharField(max_length=100)
    s_age = models.IntegerField(default=0)
    s_grade = models.IntegerField(default=0)
    s_gender = models.CharField(max_length=30)
    
    def __str__(self):
        return self.s_name

dataClass/01.pt/pt0204/sPjt/home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    print("home>index호출")
    return render(request,'index.html')

dataClass/01.pt/pt0204/sPjt/students/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from students.models import Student
from django.shortcuts import render

# 학생등록페이지
def regStudent(request):
    print("view student>reg호출")
    return render(request,'reg.html')

# 학생등록 db 저장
def regStuCon(request):
    name = request.POST['name']
    print("students view : ",name)
    major = request.POST['major']
    age = request.POST['age']
    grade = request.POST['grade']
    gender = request.POST['gender']
    qs = Student(s_name=name,s_major=major,s_age=age,s_grade=grade,s_gender=gender)
    print("views qs : ",qs)
    qs.save()
    
    # students:stuAll
    return HttpResponseRedirect(reverse('students:reg'))

dataClass/01.pt/pt0204/sPjt/home/templates/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>메인페이지</h2>
    <ul>
        <li><a href="/students/reg">학생등록페이지(기본)</a></li>
        {% comment %} <li><a href="{% url 'students:reg' %}">학생등록페이지</a></li> {% endcomment %}
        <li><a href="/admin">관리자페이지</a></li>
    </ul>
    
</body>
</html>

dataClass/01.pt/pt0204/sPjt/students/templates/reg.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>학생등록페이지</h2>
    <form action="{% url 'students:regCon' %}" method="post">
        {% csrf_token %}
        <label>학생이름</label>
        <input type="text" name="name" ><br>
        <label>학과</label>
        <input type="text" name="major"><br>
        <label>나이</label>
        <input type="text" name="age"><br>
        <label>학년</label>
        <input type="text" name="grade"><br>
        <label>성별</label>
        <input type="text" name="gender"><br>
        <input type="submit" value="저장">
        <br>
        <a href="/">메인페이지 이동</a>
    </form>
</body>
</html>