dataClass/01.pt0209/community/comm/board/urls.py
from . import views
from django.urls import include, path

app_name='board'
urlpatterns = [
    path('customer/notice/', views.notice,name='notice'),      # 공지사항 리스트
    path('chart/', views.chart,name='chart'),      # board 그래프
    path('chart_data/', views.chart_data,name='chart_data'),      # board 그래프 data
    path('<str:b_no>/event/event_view/', views.event_view,name='event_view'),  # 이벤트뷰
    
    
    path('event/comlist/', views.comlist,name='comlist'),      # 댓글 리스트
    path('event/commwrite/', views.commwrite,name='commwrite'), # 댓글 저장
    path('event/commdelete/', views.commdelete,name='commdelete'), # 댓글 삭제
    path('event/commupdateok/', views.commupdateok,name='commupdateok'), # 댓글 수정저장
    
    
    path('blist/', views.blist,name='blist'),                  # 게시판리스트
    path('bwrite/', views.bwrite,name='bwrite'),               # 글쓰기form
    path('bwriteOk/', views.bwriteOk,name='bwriteOk'),         # 글쓰기저장
    path('<str:b_no>/bview/', views.bview,name='bview'),       # 뷰페이지
    path('<str:b_no>/bmodify/', views.bmodify,name='bmodify'), # 수정form
    path('bmodifyOk/', views.bmodifyOk,name='bmodifyOk'),      # 수정저장
    path('<str:b_no>/bdelete/', views.bdelete,name='bdelete'), # 삭제
    path('<str:b_no>/breply/', views.breply,name='breply'),    # 답글쓰기form
    path('breplyOk/', views.breplyOk,name='breplyOk'),         # 답글쓰기저장
    # 공공데이터
    path('publicData/', views.publicData,name='publicData'),   # 공공데이터
    path('publicData2/', views.publicData2,name='publicData2'),   # 공공데이터
]

dataClass/01.pt0209/community/comm/comm/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('board/', include('board.urls')),
    path('member/', include('member.urls')),
    path('blockhtml/', include('blockhtml.urls')),
] 

#파일 업로드시 url구성
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dataClass/01.pt0209/community/comm/board/models.py
from datetime import datetime
from django.db import models
from member.models import Member

# 자유게시판 db
class Fboard(models.Model):
    b_no = models.IntegerField(default=0,primary_key=True)
    member = models.ForeignKey(Member,on_delete=models.DO_NOTHING,null=True)
    b_title = models.CharField(max_length=1000)
    b_content = models.TextField()
    b_date = models.DateTimeField(default=datetime.now(),blank=True)
    b_group = models.IntegerField(default=0)
    b_step = models.IntegerField(default=0)
    b_indent = models.IntegerField(default=0)
    b_hit = models.IntegerField(default=1)
    b_img = models.ImageField(blank=True)
    
    def __str__(self):
        return self.b_title

# 댓글 게시판 db    
class Comment(models.Model):
    c_no = models.IntegerField(default=0,primary_key=True)
    member = models.ForeignKey(Member,on_delete=models.DO_NOTHING,null=True)     
    fboard = models.ForeignKey(Fboard,on_delete=models.CASCADE,null=True)
    c_pw = models.CharField(max_length=10,blank=True)
    c_content = models.TextField()
    c_date = models.DateTimeField(default=datetime.now(),null=True,blank=True)
    
    def __str__(self):
        return self.c_content
    

dataClass/01.pt0209/community/comm/board/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from board.models import Fboard
from board.models import Comment
from django.db.models import Q, F
from django.core.paginator import Paginator
from member.models import Member
from django.db.models import Max,Min,Avg 
from django.core import serializers
from django.http import HttpResponse
import urllib # 한글인코딩
import requests # 웹스크롤링
import json
from django.forms.models import model_to_dict
import cx_Oracle as ora
import pandas as pd

# 차트 그리기
def chart(request):
    return render(request,'board_chart.html')

# 차트 데이터 가져오기(Ajax)
def chart_data(request):
    # c_no = request.GET.get('ajax_data')
    # qs = Comment.objects.get(c_no=c_no)
    chart_data = [{"iyear":2015,"iincome":1300},
            {"iyear":2016,"iincome":1800},
            {"iyear":2017,"iincome":1000},
            {"iyear":2018,"iincome":1100},
            {"iyear":2019,"iincome":1500},
            {"iyear":2020,"iincome":1200},
            {"iyear":2021,"iincome":1600}]
    context={'chart_data':chart_data}
    return JsonResponse(context)



# db접속정보 메소드
def connections():
    try:
        conn=ora.connect('system/1234@localhost:1521/orcl')
    except Exception as e:
        print('예외 발생')
    return conn

    
# 공지사항 리스트
def notice(request):
    # 지원번호,이름,학교,학년 4컬럼 가져옴.
    # df = pd.read_excel('C:\js_work\score.xlsx',usecols='A:D',dtype={0:str,1:str,2:str,3:str})
    df = pd.read_excel('C:\js_work\score.xlsx',usecols='A:D',dtype={0:str,1:str,2:str,3:int})
    # 데이터를 tuple()형태의 list타입으로 데이터 저장.
    # rows = [ tuple(x) for x in df.to_records(index=False) ]
    rows=[]
    for x in df.to_records(index=False):
        # 1행을 row list를 생성해서 x데이터를 입력 - int인경우 한번더 int변환
        row=[  x[0],x[1],x[2],int(x[3]) ]
        # 전체 list에 담음.
        rows.append(row)
        
    conn = connections()
    cursor = conn.cursor()
    cursor.execute('delete from score')
    sql_score = 'insert into score values(:1,:2,:3,:4)'
    # execute : 1번 구문 실행
    # executemany : 여러번 구문 실행
    cursor.executemany(sql_score,rows)
    conn.commit()
    
    # oracle db에서 df변환
    query = 'select * from score'
    df=pd.read_sql_query(query,connections())
    print(df)
    
    
    
    # # 1개 db접속
    # conn = connections()
    # print(conn.version) # conn버전 확인
    # # sqlDevelpor 창을 열었다고 생각하면 됨.
    # cursor = conn.cursor()
    # # sql구문에서 특정위치에 데이터를 받음.
    # sql_insert = 'insert into score values (:s_no,:name,:school,:grade)'
    # # sql구문 실행
    # cursor.execute(sql_insert,s_no='4번',name='김수찬',school='구로고',grade=1)
    # cursor.close()
    # conn.commit()
    
    
    # 페이지 번호가 넘어와야 함.
    # page
    qs = Fboard.objects.all()
    # objects.all() querySet 데이터를 dataFrame바로 변환
    # obeject_df3 = pd.DataFrame(qs)
    # obeject_df3 = pd.DataFrame.from_records(qs)
    obeject_df3 = pd.DataFrame.from_records(qs.values())
    print("object.all() : ",obeject_df3)
    context = {'blist':qs}
    return render(request,'customer/notice.html',context)

# 이벤트 뷰
def event_view(request,b_no):
    print("views b_no : ",b_no)
    context={"b_no":b_no}
    return render(request,'event/event_view.html',context)


# 하단댓글 리스트(Ajax) -게시글번호로 검색해서 가져옴.
def comlist(request):
    b_no = request.GET.get("b_no")
    print("views b_no : ",b_no)
    qs = Comment.objects.all().order_by('-c_no')
    clist = list(qs.values())
    return JsonResponse(clist,safe=False) # safe=False일때 list, safe=True일 때에는 dict타입이외, TypeError 예외 발생
    # clist = serializers.serialize('json', qs)
    # return HttpResponse(clist, content_type="text/json-comment-filtered")

# 하단댓글 삭제(Ajax)
def commdelete(request):
    c_no = request.GET.get('c_no')
    qs = Comment.objects.get(c_no=c_no)
    qs.delete()    
    context={'result':'댓글이 삭제되었습니다'}
    return JsonResponse(context)
 
# 댓글수정저장 
def commupdateok(request):
    c_no = request.GET.get('c_no')
    c_content = request.GET.get('c_content')
    qs = Comment.objects.get(c_no=c_no)
    qs.c_content = c_content
    qs.save()
    
    # qs = Comment.object.get(c_no=c_no)
    # qs = qs.__dict__
    # qs = del qs['_state']
    # return JsonResponse(qs, safe=False)
    
    context={
        "c_no": qs.c_no, 
        "member_id": qs.member_id, 
        "c_pw": qs.c_pw,
        "c_content":qs.c_content,
        "c_date":qs.c_date 
    }
    return JsonResponse(context)    

# 하단댓글 저장(Ajax)
def commwrite(request):
    # c_no 1씩증가 함수
    def comm_count():
        # c_no 수동으로 1씩증가해서 저장시켜줌.
        no = Comment.objects.aggregate(max_c_no=Max('c_no'))
        max_no = no['max_c_no']   # b_no 최대 번호를 찾음 1.2.5. ... 26
        max_no += 1          #최고 높은 숫자를 만들어줌. 27 = no+1
        return max_no
    # 1씩증가 함수 호출
    c_no = comm_count()
    
    id = request.session.get('session_id')  # session에서 id값 변수저장
    print("views id : ",id)
    # models 2.member객체
    member = Member.objects.get(m_id=id)
    b_no = request.GET.get("b_no")     # board b_no 변수저장
    # models 3.fboard객체
    fboard = Fboard.objects.get(b_no=b_no)
    # 4.c_pw
    c_pw = request.GET.get("c_pw")     #ajax으로 넘어온 pw 변수저장
    # 5.c_content
    c_content = request.GET.get("c_content")  #ajax으로 넘어온 content변수 저장
    # 6.c_date
    
    # 댓글저장
    qs = Comment(c_no=c_no,member=member,fboard=fboard,c_pw=c_pw,c_content=c_content)
    qs.save()
    context = {
        "c_no": qs.c_no, 
        "member_id": qs.member_id, 
        "c_pw": qs.c_pw,
        "c_content":qs.c_content,
        "c_date":qs.c_date }
    return JsonResponse(context)



#공공데이터
def publicData(request):
    nowpage = request.GET.get('nowpage',1)
    m_serviceKey ='918RE13GA7OY7ZEmUzApgbOeAcQoZ%2FaHsXWcqPAKQ9YNNPj83KOstRMRIUrCFIAcm9qj2R6b7NFZjp%2FYsYzJLg%3D%3D'
    url = 'http://api.visitkorea.or.kr/openapi/service/rest/PhotoGalleryService/galleryList?serviceKey={}&pageNo={}&numOfRows=10&MobileOS=ETC&MobileApp=AppTest&arrange=A&_type=json'.format(m_serviceKey,nowpage)
    response = requests.get(url)
    print("views response : ",response)
    # response의 내용을 text변환
    contents = response.text
    # text를 json 타입으로 변경
    json_ob = json.loads(contents)
    # json데이터 중 필요한 데이터 가져오기
    publicData = json_ob['response']['body']['items']['item']
    print(" views bodyData : ",publicData)
    context={'publicData':publicData}
    return render(request,'publicData.html',context)

#공공데이터2
def publicData2(request):
    nowpage = request.GET.get('nowpage',1)
    m_serviceKey ='918RE13GA7OY7ZEmUzApgbOeAcQoZ%2FaHsXWcqPAKQ9YNNPj83KOstRMRIUrCFIAcm9qj2R6b7NFZjp%2FYsYzJLg%3D%3D'
    url = 'https://api.odcloud.kr/api/apnmOrg/v1/list?page={}&perPage=20&serviceKey={}'.format(nowpage,m_serviceKey)
    # url에서 정보를 받아옴.
    response = requests.get(url)
    print("views response : ",response)
    # response의 내용을 text변환
    contents = response.text
    # text를 json 타입으로 변경
    json_ob = json.loads(contents)
    # json데이터 중 필요한 데이터 가져오기
    publicData = json_ob['data']
    print(" views bodyData : ",publicData)
    context={'publicData':publicData}
    return render(request,'publicData2.html',context)

# 게시판리스트
def blist(request):
    # 현재페이지 받음, 없을때 1 고정
    nowpage = int(request.GET.get('nowpage',1))  
    
    if request.method == 'GET':
        
        # 모든 게시판 내용이 담겨있음.
        qs = Fboard.objects.all().order_by('-b_group','b_step')
        # 모든게시글을 받아서 페이지 분기 - 
        paginator = Paginator(qs,10)           # 30개 1-10,2-10,3-10
        # 1,2,3 10개 blist에 담음
        blist = paginator.get_page(nowpage)
        context={'blist':blist,'nowpage':nowpage}
        return render(request,'blist.html',context) 
    else:
        category = request.POST.get('category')
        searchword = request.POST.get('searchword')
        # title검색
        if category == 'title':
            qs = Fboard.objects.filter(b_title__contains=searchword)
            # 모든게시글을 받아서 페이지 분기
            paginator = Paginator(qs,10)           # 30개 1-10,2-10,3-10
            blist = paginator.get_page(nowpage)
            context={'blist':blist,'nowpage':nowpage,'category':category,'searchword':searchword}
            return render(request,'blist.html',context)
            
        elif category == 'content':    
            qs = Fboard.objects.filter(b_content__contains=searchword)
            # 모든게시글을 받아서 페이지 분기
            paginator = Paginator(qs,10)           # 30개 1-10,2-10,3-10
            blist = paginator.get_page(nowpage)
            context={'blist':blist,'nowpage':nowpage,'category':category,'searchword':searchword}
            return render(request,'blist.html',context)
        
        elif category == 'all':
            # a and b
            # qs = Fboard.objects.filter(b_title__contains=searchword,b_content__contains=searchword)
            # a or b
            qs = Fboard.objects.filter(Q(b_title__contains=searchword) | Q(b_content__contains=searchword))
            # 모든게시글을 받아서 페이지 분기
            paginator = Paginator(qs,10)           # 30개 1-10,2-10,3-10
            blist = paginator.get_page(nowpage)       # paginator
            context={'blist':blist,'nowpage':nowpage,'category':category,'searchword':searchword}
            return render(request,'blist.html',context)
        

# 뷰페이지
def bview(request,b_no):
    qs = Fboard.objects.get(b_no=b_no)
    qs.b_hit += 1
    qs.save()
    context={'board':qs}
    return render(request,'bview.html',context)

# 수정페이지
def bmodify(request,b_no):
    qs = Fboard.objects.get(b_no=b_no)
    context={'board':qs}
    return render(request,'bmodify.html',context)

# 수정페이지저장
def bmodifyOk(request):
    b_no = request.POST.get('b_no')
    b_title = request.POST.get('b_title')
    b_content = request.POST.get('b_content')
    # 파일이름 가져오기 
    b_img = request.FILES.get('b_img','')
    print("views file : ",request.FILES)
    qs = Fboard.objects.get(b_no=b_no)
    qs.b_title = b_title
    qs.b_content = b_content
    # 파일이름 저장
    qs.b_img = b_img
    qs.save()
    # Fboard.objects.create(b_id=id,b_title=title,b_content=content)
    # context = {"board":qs}

dataClass/01.pt0209/community/comm/board/templates/customer/notice.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title> JARDIN SHOP </title>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="description" content="JARDIN SHOP" />
<meta name="keywords" content="JARDIN SHOP" />
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scaleable=no" />
<link rel="stylesheet" type="text/css" href="{% static 'css/css/reset.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/css/layout.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/css/content.css' %}" />
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/top_navi.js' %}"></script>
<script type="text/javascript" src="{% static 'js/left_navi.js' %}"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
<script type="text/javascript" src="{% static 'js/common.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script type="text/javascript" src="{% static 'js/idangerous.swiper-2.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.anchor.js' %}"></script>


</head>
<body>

<div id="allwrap">
<div id="wrap">

	<div id="header">
		
		<div id="snbBox">
			<h1><img src="{% static '/images/images/txt/logo.gif'%}" alt="JARDIN SHOP" /></h1>
			<div id="quickmenu">
				<div id="mnaviOpen"><img src="{% static '/images/images/btn/btn_mnavi.gif'%}" width="33" height="31" alt="메뉴열기" /></div>
				<div id="mnaviClose"><img src="{% static '/images/images/btn/btn_mnavi_close.gif'%}" width="44" height="43" alt="메뉴닫기" /></div>
				<ul>
					<li><a href="#">EVENT</a></li>
					<li><a href="#">CUSTOMER</a></li>
					<li><a href="#">COMMUNITY</a></li>
				</ul>
			</div>
			<div id="snb">
				<ul>
					<li><a href="#">LOGIN</a></li>
					<li><a href="#">JOIN</a></li>
					<li><a href="#">MY PAGE</a></li>
					<li><a href="#">CART</a></li>
				</ul>

				<div id="search">
					<input type="text" class="searchType" />
					<input type="image" src="{% static '/images/images/btn/btn_main_search.gif' %}" width="23" height="20" alt="검색하기" />
				</div>
			</div>
		</div>
	</div>


	<!-- GNB -->
	<div id="gnb">
		
		<div id="top">
			<ul>
				<li class="brand t1"><a href="#" id="topNavi1">JARDIN’s BRAND</a>
					<ul id="topSubm1">
						<li><a href="#">클래스</a></li>
						<li><a href="#">홈스타일 카페모리</a></li>
						<li><a href="#">드립커피백</a></li>
						<li><a href="#">카페리얼 커피</a></li>
						<li><a href="#">오리지널커피백</a></li>
						<li><a href="#">카페리얼 음료</a></li>
						<li><a href="#">마일드커피백</a></li>
						<li><a href="#">워터커피</a></li>
						<li><a href="#">카페포드</a></li>
						<li><a href="#">모히또파티</a></li>
						<li><a href="#">테이크아웃 카페모리</a></li>
						<li><a href="#">포타제</a></li>
					</ul>
				</li>
				<li class="t2"><a href="#" id="topNavi2">원두</a>
					<ul id="topSubm2">
						<li><a href="#">클래스</a></li>
						<li><a href="#">로스터리샵</a></li>
						<li><a href="#">커피휘엘</a></li>
						<li><a href="#">산지별 생두</a></li>
					</ul>
				</li>
				<li class="t1"><a href="#" id="topNavi3">원두커피백</a>
					<ul id="topSubm3">
						<li><a href="#">드립커피 로스트</a></li>
						<li><a href="#">오리지널커피백</a></li>
						<li><a href="#">마일드커피백</a></li>
					</ul>
				</li>
				<li class="t2"><a href="#" id="topNavi4">인스턴트</a>
					<ul id="topSubm4">
						<li><a href="#">까페모리</a></li>
						<li><a href="#">홈스타일카페모리</a></li>
						<li><a href="#">포타제</a></li>
					</ul>
				</li>
				<li class="t1"><a href="#" id="topNavi5">음료</a>
					<ul id="topSubm5">
						<li><a href="#">까페리얼</a></li>
						<li><a href="#">워터커피</a></li>
						<li><a href="#">모히또</a></li>
					</ul>
				</li>
				<li class="t2"><a href="#" id="topNavi6">커피용품</a>
					<ul id="topSubm6">
						<li><a href="#">종이컵</a></li>
						<li><a href="#">커피필터</a></li>
						<li><a href="#">머신 등</a></li>
					</ul>
				</li>
				<li class="t1"><a href="#" id="topNavi7">선물세트</a></li>
				<li class="t2"><a href="#" id="topNavi8">대량구매</a></li>
			</ul>
		</div>

		<script type="text/javascript">initTopMenu();</script>
	</div>
	<!-- //GNB -->

	<!-- container -->
	<div id="container">

		<div id="location">
			<ol>
				<li><a href="#">HOME</a></li>
				<li><a href="#">CUSTOMER</a></li>
				<li class="last">NOTICE</li>
			</ol>
		</div>
		
		<div id="outbox">		
			<div id="left">
				<div id="title2">CUSTOMER<span>고객센터</span></div>
				<ul>	
					<li><a href="#" id="leftNavi1">NOTICE</a></li>
					<li><a href="#" id="leftNavi2">1:1문의</a></li>
					<li><a href="#" id="leftNavi3">FAQ</span></a></li>
					<li class="last"><a href="#" id="leftNavi4">이용안내</a></li>
				</ul>			
			</div><script type="text/javascript">initSubmenu(1,0);</script>


			<!-- contents -->
			<div id="contents">
				<div id="customer">
					<h2><strong>NOTICE</strong><span>쟈뎅샵 소식을 전해드립니다.</span></h2>
					
					<div class="orderDivMt">
						<table summary="NO, 제목, 등록일, 조회수 순으로 공지사항을 조회 하실수 있습니다." class="orderTable2" border="1" cellspacing="0">
							<caption>공지사항 보기</caption>
							<colgroup>
							<col width="10%" class="tnone" />
							<col width="*" />
							<col width="14%" class="tw25" />
							<col width="14%" class="tnone" />
							</colgroup>
							<thead>
								<th scope="col" class="tnone">NO.</th>
								<th scope="col">제목</th>
								<th scope="col">등록일</th>
								<th scope="col" class="tnone">조회수</th>
							</thead>

							<tbody>
								<!-- 게시판 반복 -->
								{% if blist %}
								    {% for board in blist %}
										<tr>
											<td class="tnone">{{ board.b_no }}</td>
											<td class="left">
												<a href="{% url 'board:event_view' board.b_no  %}">{{ board.b_title }}</a>
												<img src="{% static '/images/images/ico/ico_new.gif'%}" alt="NEW" />
											</td>
											<td>{{ board.b_date|date:'Y-m-d' }}</td>
											<td class="tnone right">{{ board.b_hit }}</td>
										</tr>
									{% endfor %}
								{% else %}
									<tr>
										<td class="tnone"></td>
										<td class="left">
											<a href="#">데이터 없음.</a>
										</td>
										<td></td>
										<td class="tnone right"></td>
									</tr>
								{% endif %}
							</tbody>
						</table>
					</div>
						


					<div class="btnAreaList">
						<!-- 페이징이동1 -->
						<div class="allPageMoving1">

						<a href="#" class="n"><img src="{% static '/images/images/btn/btn_pre2.gif'%}" alt="처음으로"/></a><a href="#" class="pre"><img src="{% static '/IMAGES/images/btn/btn_pre1.gif'%}" alt="앞페이지로"/></a>
						<strong>1</strong>
						<a href="#">2</a>
						<a href="#">3</a>
						<a href="#">4</a>
						<a href="#">5</a>
						<a href="#" class="next"><img src="{% static '/images/images/btn/btn_next1.gif'%}" alt="뒤페이지로"/></a><a href="#" class="n"><img src="{% static '/IMAGES/images/btn/btn_next2.gif'%}" alt="마지막페이지로"/></a>

						</div>
						<!-- //페이징이동1 -->
					</div>

					<div class="searchWrap">
						<div class="search">
							<ul>
								<li class="web"><img src="{% static '/IMAGES/images/txt/txt_search.gif'%}" alt="search" /></li>
								<li class="se">
									<select>
										<option value="" />제목</option>
									</select>
								</li>
								<li><input type="text" class="searchInput" /></li>
								<li class="web"><a href="#"><img src="{% static '/IMAGES/images/btn/btn_search.gif'%}" alt="검색" /></a></li>
								<li class="mobile"><a href="#"><img src="{% static '/IMAGES/images/btn/btn_search_m.gif'%}" alt="검색" /></a></li>
							</ul>
						</div>
					</div>
					<!-- //포토 구매후기 -->


				</div>
			</div>
			<!-- //contents -->

		</div>
	</div>
	<!-- //container -->




	<div id="footerWrap">
		<div id="footer">
			<div id="fnb">
				<ul>
					<li class="left"><a href="#">개인정보취급방침</a></li>
					<li><a href="#">이용약관</a></li>
					<li class="left"><a href="#">이메일무단수집거부</a></li>
					<li><a href="#">고객센터</a></li>
					<li class="left brand"><a href="#">쟈뎅 브랜드 사이트</a></li>
				</ul>
			</div>
			
			<div id="finfo">
				<div id="flogo"><img src="{% static '/IMAGES/images/txt/flogo.gif'%}" alt="JARDIN THE COFFEE CREATOR, SINCE 1984" /></div>
				<address>
					<ul>
						<li>㈜쟈뎅</li>
						<li>대표자 윤영노</li>
						<li class="tnone">주소 서울시 강남구 논현동 4-21번지 영 빌딩</li>
						<li class="webnone">소비자상담실 02)546-3881</li>
						<li>사업자등록번호 211-81-24727</li>
						<li class="tnone">통신판매신고 제 강남 – 1160호</li>
						<li class="copy">COPYRIGHT © 2014 JARDIN <span>ALL RIGHTS RESERVED.</span></li>
					</ul>
				</address>

				<div id="inicis"><img src="{% static '/IMAGES/images/ico/ico_inicis.png'%}" alt="이니시스 결제시스템" /></div>
			</div>
		</div>
	</div>



</div>
</div>
</body>
</html>