dataClass/01.pt/pt0208/bpjt/fboard/board/urls.py
from . import views
from django.urls import path

app_name='board'
urlpatterns = [
    path('blist/',views.blist,name='blist'),
    path('bwrite/',views.bwrite,name='bwrite'),
    path('bwriteOk/',views.bwriteOk,name='bwriteOk'),
    path('<str:b_no>/bview/',views.bview,name='bview'),
    path('<str:b_no>/bmodify/',views.bmodify,name='bmodify'), 
    path('bmodifyOk/',views.bmodifyOk,name='bmodifyOk' ),  # 수정저장
    path('<str:b_no>/bdelete/',views.bdelete,name='bdelete'), 
]

dataClass/01.pt/pt0208/bpjt/fboard/fboard/urls.py
from django.contrib import admin
from django.urls import include, path

# project urls 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('board/', include('board.urls')),
    path('member/', include('member.urls')),
]

dataClass/01.pt/pt0208/bpjt/fboard/home/urls.py
from . import views
from django.urls import path

app_name=''
urlpatterns = [
    path('',views.index,name='index' ),
]

dataClass/01.pt/pt0208/bpjt/fboard/member/urls.py
from . import views
from django.urls import path

app_name='member'
urlpatterns = [
    path('login/',views.login,name='login'),
    path('loginOk/',views.loginOk,name='loginOk'),
    path('logout/',views.logout,name='logout'),
    # path('mwrite/',views.mwrite,name='mwrite'),
]

dataClass/01.pt/pt0208/bpjt/fboard/board/models.py
from datetime import datetime
from django.db import models

# Create your models here.
class Freeboard(models.Model):
    b_no = models.AutoField(primary_key=True)
    b_id = models.CharField(max_length=100) 
    b_title = models.CharField(max_length=1000)
    b_content = models.TextField()
    b_date = models.DateTimeField(default=datetime.now(),blank=True)
    b_hit = models.IntegerField(default=1)
    # b_img = models.ImageField(blank=True)
    
    def __str__(self):
        return self.b_title

dataClass/01.pt/pt0208/bpjt/fboard/member/models.py
from django.db import models

# Create your models here.
class Member(models.Model):
    m_id = models.CharField(max_length=100,primary_key=True)
    m_pw = models.CharField(max_length=100)
    m_name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.m_name

dataClass/01.pt/pt0208/bpjt/fboard/board/views.py
import datetime
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from board.models import Freeboard

# 게시판리스트
def blist(request):
    qs = Freeboard.objects.all().order_by('-b_no')
    context = {'blist':qs }
    return render(request,'blist.html',context)

# 게시판 글쓰기
def bwrite(request):
    return render(request,'write_view.html')

# 게시판글쓰기 저장
def bwriteOk(request):
    id = request.POST.get('id')
    title = request.POST.get('title')
    content = request.POST.get('content')
    qs = Freeboard(b_id=id,b_title=title,b_content=content)
    qs.save()
    
    return HttpResponseRedirect(reverse('board:blist'))

# 게시판 뷰페이지
def bview(request,b_no):
    qs = Freeboard.objects.get(b_no=b_no)
    qs.b_hit = qs.b_hit+1
    qs.save()
    context={'board':qs}
    return render(request,'content_view.html',context)

# 게시판 수정페이지
def bmodify(request,b_no):
    qs = Freeboard.objects.get(b_no=b_no)
    context={'board':qs}
    return render(request,'modify_view.html',context)

# 게시판수정 저장
def bmodifyOk(request):
    b_no = request.POST.get('b_no')
    title = request.POST.get('title')
    content = request.POST.get('content')
    qs = Freeboard.objects.get(b_no=b_no)
    qs.b_title = title
    qs.b_content = content
    qs.b_date = datetime.datetime.now()   #2개 1개 최초등록, 수정업데이트
    # qs.b_date = timezone.now()    #2개 1개 최초등록, 수정업데이트
    qs.save()
    
    return HttpResponseRedirect(reverse('board:blist'))

# 게시판 삭제
def bdelete(request,b_no):
    qs = Freeboard.objects.get(b_no=b_no)
    qs.delete()
    return HttpResponseRedirect(reverse('board:blist'))

dataClass/01.pt/pt0208/bpjt/fboard/home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'index.html')

dataClass/01.pt/pt0208/bpjt/fboard/member/views.py
from django.shortcuts import redirect, render, get_object_or_404
from member.models import Member

# 로그인 페이지
def login(request):
    return render(request,'login.html')

# 로그인 체크
def loginOk(request):
    id = request.POST.get("id")
    pw = request.POST.get("pw")
    # id, pw가 일치하지 않을때 예외 처리
    try:
        member = Member.objects.get(m_id=id,m_pw=pw)
    except Member.DoesNotExist:
        member = None
    # member에 해당 id가 있으면
    if member:
        id = member.m_id
        name = member.m_name
        request.session['session_id']=id  # {'session_id':'aaa'}
        request.session['session_name']=name  # {'session_name':'name'}
        context ={'msg':'로그인 성공!!'}
        return render(request,'index.html',context)
    else:
        context ={'msg':'아이디와 패스워드가 일치하지 않습니다.'}
        return render(request,'login.html',context)
    
# 로그아웃
def logout(request):
    if request.session.get('session_id'):
        request.session.clear()              # 섹션모두 삭제
        # del request.session['session_id']  # 해당섹션만 삭제 
    return redirect('/')

dataClass/01.pt/pt0208/bpjt/fboard/home/templates/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
        // msg가 있으면 출력시킴
        if('{{msg}}' != ''){
            alert('{{msg}}')
        }
    </script>
</head>
<body>
    <h2>메인페이지</h2>
    {% if request.session.session_id %}
        <p>{{request.session.session_name}}님 환영합니다.</p>
        <ul>
            <li><a href="{% url 'board:blist' %}">게시판리스트</a></li>
            <li><a href="/admin">관리자페이지</a></li>
            <li><a href="{% url 'member:logout' %}">로그아웃</a></li>
            <li>회원가입</li>
        </ul>
    {% else %}
        <p>로그인을 하셔야 합니다.</p>
        <ul>
            <li>회원가입</li>
            <li><a href="{% url 'member:login' %}">로그인</a></li>
        </ul>
    {% endif %}
    
</body>
</html>

dataClass/01.pt/pt0208/bpjt/fboard/member/templates/login.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <style>
        *{
            margin: 0;
            padding: 0;
        }
        body{
            position: relative;
            height: 100%;
            background: #f5f6f7;
        }
        #wrap{
            position: relative;
            min-height: 100%;
            font-size: 12px;
        }
        #header{
            position: relative;
            box-sizing: border-box;
            height: 168px;
            padding: 62px 0 0;
            width: 768px;
            margin: 0 auto;
        }

        #h_logo{
            display: block;
            overflow: hidden;
            width: 231px;
            height: 44px;
            margin: 0 auto;
            font-size: 15px;
            color: transparent;
            background: url("https://static.nid.naver.com/images/ui/login/pc_sp_login_190522.png") no-repeat -1px -1px;
        }
        #container{
            padding-bottom: 50px;
            min-height: 185px;
        }
        #content{
            width: 460px;
            margin: 0 auto;
            padding-bottom: 30px;
        }
        .id_area{
            position: relative;
        }
        .input_row{
            position: relative;
            height: 29px;
            margin: 0 0 14px;
            padding: 10px 35px 10px 15px;
            border: solid 1px #dadada;
            background: #fff;
        }
        .input_box{
            display: block;
            overflow: hidden;
        }

        .int{
            font-size: 15px;
            line-height: 16px;
            position: relative;
            z-index: 9;
            width: 100%;
            height: 16px;
            padding: 7px 0 6px;
            color: #000;
            border: none;
            background: #fff;
            appearance: none;
        }
        .btn_login{
            display: block;
            width: 100%;
            height: 61px;
            margin:30px 0 14px;
            padding-top: 1px;
            border: none;
            background: #03c75a;
            text-align: center;
            color: #fff;
            font-size: 20px;
            font-weight: 700;
            line-height: 61px;
            cursor: pointer;
        }
    </style>
    <script>
        // msg가 있으면 출력시킴
        if('{{msg}}' != ''){
            alert('{{msg}}')
        }
        
    </script>


</head>
<body>
<div id="wrap">
    <div id="header">
        <h1>
            <a href="#" id="h_logo"></a>
        </h1>
    </div>
    <div id="container">
        <div id="content">
            <div style="margin-bottom: 7px"></div>
            <form action="{% url 'member:loginOk' %}" method="post">
                {% csrf_token %}
                <fieldset style="border: 0">
                    <div class="id_area">
                        <div class="input_row" id="id_area">
                            <span class="input_box">
                                <input type="text" name="id" id="id" class="int" placeholder="아이디">
                            </span>
                        </div>
                    </div>
                    <div class="pw_area">
                        <div class="input_row" id="pw_area">
                            <span class="input_box">
                                <input type="text" name="pw" id="pw" class="int" placeholder="비밀번호">
                            </span>
                        </div>
                    </div>
                    <input class="btn_login" type="submit" id="loginBtn" value="로그인">
                </fieldset>
            </form>
        </div>
    </div>
</div>
</body>
</html>